import json
import unittest

from cad_core import (
    CadDocument,
    bounds,
    export_dxf_text,
    export_svg_text,
    item_segments,
    polygon_area,
    quantity_report,
    segment_intersection,
)


class GeometryTests(unittest.TestCase):
    def test_segment_intersection_inside_segments(self):
        self.assertEqual(segment_intersection((0, 0), (10, 10), (0, 10), (10, 0)), (5.0, 5.0))

    def test_segment_intersection_parallel_returns_none(self):
        self.assertIsNone(segment_intersection((0, 0), (10, 0), (0, 1), (10, 1)))

    def test_area_segments_close_polygon(self):
        item = {"type": "area", "points": [(0, 0), (10, 0), (10, 10)]}
        self.assertEqual(len(item_segments(item)), 3)
        self.assertEqual(item_segments(item)[-1], ((10, 10), (0, 0)))

    def test_polygon_area(self):
        self.assertEqual(polygon_area([(0, 0), (10, 0), (10, 10), (0, 10)]), 100)


class DocumentTests(unittest.TestCase):
    def test_document_round_trip_normalizes_points(self):
        doc = CadDocument()
        doc.add_item({"type": "line", "layer": "راه", "points": [(0, 0), (1, 1)]})
        data = json.loads(json.dumps(doc.to_data("شب مهندسی", "m")))
        loaded = CadDocument()
        loaded.load_data(data)
        self.assertEqual(loaded.items[0]["points"], [(0, 0), (1, 1)])
        self.assertEqual(loaded.id_counter, doc.id_counter)

    def test_undo_redo_item_add(self):
        doc = CadDocument()
        doc.add_item({"type": "line", "layer": "راه", "points": [(0, 0), (1, 1)]})
        self.assertEqual(len(doc.items), 1)
        self.assertTrue(doc.undo())
        self.assertEqual(doc.items, [])
        self.assertTrue(doc.redo())
        self.assertEqual(len(doc.items), 1)


class ExportTests(unittest.TestCase):
    def setUp(self):
        self.layers = {
            "راه": {"visible": True, "color": "#ffffff"},
            "اندازه‌گذاری": {"visible": True, "color": "#00ff00"},
        }
        self.items = [
            {"type": "line", "layer": "راه", "points": [(0, 0), (10, 0)], "width": 2},
            {"type": "area", "layer": "اندازه‌گذاری", "points": [(0, 0), (5, 0), (5, 5)], "width": 1},
        ]

    def test_bounds(self):
        self.assertEqual(bounds(self.items), (0, 0, 10, 5))

    def test_quantity_report_includes_totals(self):
        report = quantity_report(self.items, "m")
        self.assertIn("تعداد کل آیتم‌ها: 2", report)
        self.assertIn("تفکیک لایه‌ها", report)

    def test_svg_export_contains_metadata_and_polygon(self):
        svg = export_svg_text(self.items, self.layers)
        self.assertIn("Generated by CivilCAD Pro MVP", svg)
        self.assertIn("<polygon", svg)

    def test_dxf_export_closes_area(self):
        dxf = export_dxf_text(self.items)
        self.assertIn("EOF", dxf)
        self.assertGreaterEqual(dxf.count("LINE"), 4)


if __name__ == "__main__":
    unittest.main()
